services:
    php:
        image: ${IMAGES_PREFIX:-ghcr.io/yohang/uuid-benchmark/}php:${IMAGE_VERSION:-latest}
        build:
            context: .
            target: php
            args:
                EXTERNAL_USER_ID: ${EXTERNAL_USER_ID:-33}
        restart: unless-stopped
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}
            DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}
        volumes:
            - caddy_data:/data
            - caddy_config:/config

    database:
        image: postgres:17-trixie
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app_int}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app_int}", "-U", "${POSTGRES_USER:-app}" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - database_data:/var/lib/postgresql/data:rw

volumes:
    caddy_data:
    caddy_config:
    database_data:
