services:
  php:
    depends_on: [ database ]
    volumes:
      - ./:/app
      - ./infra/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./infra/frankenphp/conf.d/20-app.ini-dev:/usr/local/etc/php/app.conf.d/20-app.ini:ro
    environment:
      CADDY_SERVER_EXTRA_DIRECTIVES: tls /app/infra/frankenphp/tls/cert.pem /app/infra/frankenphp/tls/key.pem
      FRANKENPHP_WORKER_CONFIG: watch
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_ENV: "${APP_ENV:-dev}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true
    command: [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--watch" ]
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp


  database:
    ports:
      - target: 5432
        published: ${DATABASE_PORT:-5432}
        protocol: tcp
