name: CI

on:
    push:
        branches: [ '*' ]
    pull_request: ~
    workflow_dispatch: ~

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Build docker images (branch or tag name)
                uses: docker/bake-action@v6
                env:
                    IMAGE_VERSION: ${{ github.ref_name }}
                with:
                    pull: true
                    push: true
                    load: true
                    files: |
                        compose.yaml
                        compose.override.yaml
                    set: |
                        *.cache-from=type=gha,scope=${{ github.ref }}
                        *.cache-from=type=gha,scope=refs/heads/main
                        *.cache-to=type=gha,scope=${{ github.ref }},mode=max
            -   name: Build docker images (latest if main)
                uses: docker/bake-action@v6
                if: github.ref == 'refs/heads/main'
                env:
                    IMAGE_VERSION: ${{ github.ref_name }}
                with:
                    pull: true
                    push: true
                    load: true
                    files: |
                        compose.yaml
                        compose.override.yaml
                    set: |
                        *.cache-from=type=gha,scope=${{ github.ref }}
                        *.cache-from=type=gha,scope=refs/heads/main
                        *.cache-to=type=gha,scope=${{ github.ref }},mode=max

    benchmark:
        name: Benchmark
        runs-on: ubuntu-latest
        needs: [ build ]
        strategy:
            matrix:
                id_type: [ int, uuid_v1, uuid_v4, uuid_v6, uuid_v7 ]
                number_of_root_entity: [ 1_000, 10_000, 100_000 ]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Run services
                run: docker compose up -d --wait
            -   name: Run benchmark
                run: docker compose exec -e ID_TYPE=${{ matrix.id_type }} -e NUMBER_OF_ROOT_ENTITY=${{ matrix.number_of_root_entity }} php composer benchmark
