name: CI

on:
    push:
        branches: [ '*' ]
    pull_request: ~
    workflow_dispatch: ~

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -   name: Build docker images
                uses: docker/bake-action@v5
                with:
                    pull: true
                    push: true
                    load: true
                    files: compose.yaml compose.override.yaml
                    set: |
                        php.cache-from=type=gha,scope=php-${{ github.ref }}
                        php.cache-from=type=gha,scope=php-refs/heads/main
                        php.cache-to=type=gha,scope=php-${{ github.ref }},mode=max

    benchmark:
        name: Benchmark
        runs-on: ubuntu-24.04
        needs: build
        strategy:
            matrix:
                id_type: [ int, uuid1, uuid4, uuid6, uuid7 ]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Run services
                run: docker compose up -d --wait
            -   name: Run benchmark
                run: docker compose exec -e ID_TYPE=${{ matrix.id_type }} php composer composer benchmark
